pulsar:
  service:
    url: pulsar://broker.pulsar:6650
  admin:
    service:
      url: http://proxy.pulsar:8080

server:
  port: 8085

eureka:
  instance:
    hostname: datasource-api.api

logging:
  level:
    root: info
