pulsar:
  service:
    url: pulsar://broker.pulsar:6650
  admin:
    service:
      url: http://pulsar-broker.pulsar:8080

eureka:
  instance:
    hostname: function-api.api

spring:
  application:
    name: function-api
