pulsar:
  service:
    url: pulsar://proxy.pulsar:6650
  admin:
    service:
      url: http://proxy.pulsar:8080

eureka:
  instance:
    hostname: function-api.api

spring:
  application:
    name: function-api
  data:
    elasticsearch:
      cluster-nodes: geoant-service.geoant:9200
      cluster-name: geoant

server:
  port: 80

