pulsar:
  service:
    url: pulsar://broker.pulsar.svc.cluster.local:6650
  admin:
    service:
      url: https://proxy.pulsar:8080

eureka:
  instance:
    hostname: function-api.api

spring:
  application:
    name: function-api
