pulsar:
  service:
    url: pulsar://tcp.theground.io:6650
  admin:
    service:
      url: https://broker.pulsar:8080

eureka:
  instance:
    hostname: function-api.api

spring:
  application:
    name: function-api
