pulsar:
  service:
    url: pulsar://broker.pulsar:6650
  admin:
    service:
      url: https://broker.pulsar:8080
  topic:
    function-upload: persistent://theground/api/function-upload
    file-upload: persistent://theground/data/gdelt_c



server:
  port: 80

eureka:
  instance:
    hostname: registry-api.api

spring:
  application:
    name: registry-api










