eureka:
  instance:
    hostname: stream-api.api
  client:
    service-url:
      defaultZone: http://discovery-service.api:8761/eureka
    fetch-registry: true
    register-with-eureka: true


logging:
  level:
    root: info
    io.theground.streamapi: debug

spring:
  application:
    name: stream-api
  main:
    web-application-type: reactive
  data:
    elasticsearch:
      cluster-nodes: tcp.theground.io:9200
      cluster-name: geoant
    cassandra:
      contact-points: geoant-cassandra.geoant
  cloud:
    dataflow:
      client:
        serverUri: http://scdf-server.scdf:443

server:
  port: 80
