server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: function-api
        uri: http://function-api.api/functions
        predicates:
        - Path=/functions*,/functions/**
      - id: topic-api
        uri: http://topic-api.api/topics
        predicates:
        - Path=/topics*,/topics/**


