pulsar:
  service:
    url: pulsar://proxy.pulsar:6650
  admin:
    service:
      url: http://proxy.pulsar:8080

logging:
  level:
    root: info

spring:
  application:
    name: topic-api
  main:
    web-application-type: reactive

eureka:
  instance:
    hostname: topic-api.api
server:
  port: 80
