pulsar:
  service:
    url: pulsar://broker.pulsar:6650
  admin:
    service:
      url: http://broker.pulsar:8080

logging:
  level:
    root: info

spring:
  application:
    name: topic-api
  main:
    web-application-type: reactive

eureka:
  instance:
    hostname: topic-api.api
